package bhavana.agenticsdlc.platform.workflow.domain;

public enum TaskType {
    REQUIREMENT_UNDERSTANDING,
    AMBIGUITY_DETECTION,
    REPOSITORY_ANALYSIS,
    TASK_DECOMPOSITION,
    ARCHITECTURE_DESIGN,
    IMPLEMENTATION,
    TEST_GENERATION,
    PATCH_POLICY,
    PATCH_APPLICATION,
    VALIDATION,
    REPAIR,
    DOCUMENTATION,
    SECURITY_RISK_REVIEW,
    RELEASE_READINESS,
    HUMAN_GATE,
    ROLLBACK
}

