package bhavana.agenticsdlc.platform.agent;
public enum AgentRole { REQUIREMENT_UNDERSTANDING, AMBIGUITY_CLARIFICATION, REPOSITORY_ANALYSIS, TASK_DECOMPOSITION, ARCHITECTURE_DESIGN, IMPLEMENTATION, TEST_GENERATION, VALIDATION, REPAIR, DOCUMENTATION, SECURITY_RISK_REVIEW, RELEASE_READINESS }
